main:
  seed: DBCG6L4ZYA
  output_path: output/
  history_config:
    content: "Olá a todos, preciso compartilhar algo que tem me consumido por dentro. Hoje, recebi uma ligação\
        \ do meu irmão, só que não era uma conversa qualquer. Ele me ligou PARA ME PARABENIZAR PELO MEU ANIVERSÁRIO.\
        \ Sim, pelos meus 30 anos! Mas o que ele não sabe, ou talvez não se importe, é que estou vivendo em\
        \ um abrigo há seis meses.\n\nPara quem não sabe, a vida tem sido uma luta. Depois de uma separação\
        \ conturbada, perdi minha casa e meus sonhos de uma vida estável. O engraçado (ou triste) é que ele\
        \ mora a apenas 15 minutos de onde estou, em uma casa enorme, com um lindo jardim e espaço de sobra.\
        \ Quando pedi para ficar lá só por um tempo, a resposta dele foi \"NÃO, ESTOU OCUPADO\", mesmo tendo\
        \ um quarto vago. \n\nEnquanto ele festejou o meu aniversário, eu estava em uma pequena cama em um\
        \ lugar frio, cercado por estranhos. Não consegui entender como ele pode simplesmente ignorar minha\
        \ situação e ainda assim ligar para dizer \"Feliz Aniversário!\". Onde está a compaixão? O que eu\
        \ fiz para merecer isso? Se a vida está difícil para mim, que ele tenha ao menos o bom senso de não\
        \ fazer questão de me lembrar disso na data em que deveria ser uma celebração. \n\nAcho que o que\
        \ mais me dói é a indiferença. Eu gostaria de ser ouvido, de encontrar alguém que se importasse, não\
        \ só em datas festivas. Na verdade, gostaria de ter a chance de ouvir dele que tudo ficaria bem, que\
        \ ele estaria ali por mim. Mas não... ele só aparece em momentos festivos. Então, eu me pergunto,\
        \ o que eu sou para ele? Um número? Um dia no calendário? \n\nEnfim, decidi compartilhar isso para\
        \ que outros que estejam passando por algo assim saibam que não estão sozinhos. Vamos lembrar que\
        \ as palavras têm poder e que, às vezes, um simples gesto pode mudar a vida de alguém. Obrigado por\
        \ me ouvirem e Feliz Aniversário para mim, eu apenas espero um dia ter a mesma felicidade."
    file_name: a_ligacao_do_silencio
    title: A ligação do silêncio
  video_config:
    low_quality: false
    youtube_channel_id: UC4r6nalq_1-9rc80qdVLatQ
    watermark_path: assets/watermark.png
    cover_duration: 5
    end_silece_seconds: 3
    padding: 50
    cover_duration: 5
    width: 1080
    height: 1920
  cover_config:
    subtitle: "Desabafo"
    title_font_family: Sigmar
    subtitle_font_family: Sigmar
    title_font_size: 60
    subtitle_font_size: 50
    title_font_color: "#F5F5F5"
    subtitle_font_color: "#EEDE2F"
    background_color: "#0049B7"
    rounding_radius: 30
    padding: 50