main:
  seed: RME1TKW8UG
  output_path: output/
  history_config:
    source: config
    histories:
    -   content: 'Bom dia comunidade, espero que estejam bem. Esse é um relato que aconteceu comigo no ano
            passado, mais especificamente em Julho de 2024. Alerta de textão! Férias da faculdade, conheci
            uma garota indo para o caminho do trabalho, sempre ficávamos um do lado do outro no ponto de ônibus
            mas não trocávamos uma única palavra, justamente por eu ser muito tímido. As vezes nosso olhar
            se encontrava, mas eu simplesmente não conseguia chegar nela por ser muito atraente, até que em
            determinado momento eu ganhei poderes divinos e puxei assunto com ela. Daí em diante começamos
            a nos conhecer. Ela é uma garota MUITO linda, não tem corpão, mas suas roupas e seu rosto fazem
            parecer ser uma modelo. A própria faz curso de modelo. Ficamos conversando durante 4 dias no ponto
            de ônibus, à noite, e a madrugada inteira pelo Instagram. Ela estava dando claros sinais de interesse,
            perguntava de mim, do meu dia, puxava assunto primeiro, me mandava selfies em casa (do nada),
            me elogiava, me deu apelido de ''amor'', etc, etc, etc. Em resumo, estava sendo uma garota tão
            legal quanto a beleza.

            Curta e me siga para parte 2'
        description: ''
        file_name: fugi_no_meio_do_encontro_com_a_garota_1
        gender: male
        reddit_community: r/RelatosDoReddit
        reddit_community_url_photo: https://styles.redditmedia.com/t5_72ljkj/styles/communityIcon_nhey0a1kj0jc1.png
        reddit_post_author: upentakill
        title: Fugi no meio do encontro com a garota - Parte 1
    -   content: 'Chamei ela para jantar, ela aceitou. Minha ideia era irmos no Outback (mas não falei o local
            que iríamos). Me arrumei bem, passei perfume, cheguei na casa dela com o carro do meu pai, um
            Chevrolet Celta em perfeito estado, lindo, polido, interior limpo e cheiroso. O carro estava zero.
            Saí do carro, abri a porta para ela, deixei ela colocar a playlist dela no multi-mídia que meu
            pai pagou para instalar, e fomos pro shopping. Se trocamos 6 frases no caminho foi muito, eu realmente
            estava tentando puxar assuntos, mas era respondido com respostas curtas como: ''Pois é'', ''aham'',
            ''então''… Dali eu vi que iria ser um date difícil. Chegamos no shopping, estava uma noite linda.
            Estacionei e entramos, continuei tentando puxar assunto, mas sem sucesso. Segurei na mão dela
            para caminharmos de mãos dadas, mas percebi que ela não estava apertando minha mão, deixava a
            palma aberta como se eu estivesse a carregando. Então, decidi soltar, pois fiquei com medo de
            estar deixando ela desconfortável. Entramos no Outback, o garçom nos disponibilizou uma mesa e
            ficamos ali sentados vendo o cardápio digital. Eu continuei tentando puxar assunto, mas novamente
            sem sucesso, apenas curtas respostas. Parecia que ela não estava gostando do rolê, parecia um
            robô. Até que cansei e decidi ir embora. Eu simplesmente não iria conseguir pagar um jantar para
            uma pessoa assim. Disse que iria ao banheiro, no caminho encontrei-me com o garçom e expliquei
            a situação. Pedi para ele falar a ela que eu precisei sair de urgência e lhe dei uma gorjeta.
            O garçom entendeu meu ponto e aceitou. Por fim, peguei o carro e fui embora. Eu realmente não
            sei se foi a melhor maneira de sair. Não sei se eu deveria ter sido direto e dito o que estava
            me incomodando. Não mandei mais mensagem para ela, e vice-versa. Até hoje nos encontramos todo
            dia no mesmo ponto de ônibus, mas não trocamos sequer uma única palavra. Parece até que nunca
            nos falamos. Há pouco tempo percebi que ela parou de me seguir no Instagram, mas tudo bem. Bom,
            esse foi o relato que eu gostaria de compartilhar com vocês. Muito obrigado a quem leu até aqui.'
        description: ''
        file_name: fugi_no_meio_do_encontro_com_a_garota_2
        gender: male
        reddit_community: r/RelatosDoReddit
        reddit_community_url_photo: https://styles.redditmedia.com/t5_72ljkj/styles/communityIcon_nhey0a1kj0jc1.png
        reddit_post_author: upentakill
        title: Fugi no meio do encontro com a garota - Parte 2
  video_config:
    low_quality: false
    youtube_channel_id: UCIXTGJvqvxWoWWstA66a2JQ
    watermark_path: assets/watermark.png
    cover_duration: 5
    end_silece_seconds: 3
    padding: 60
    width: 1080
    height: 1920
  cover_config:
    title_font_size: 100