proxies:
  reddit_config:
    type: json
  cover_config:
    title_font_size: 150
  image_generation_config:
    type: leonardo
    model_id: "de7d3faf-762f-48e0-b3b7-9d0ac3a3fcf3"
    style_uuid: "093accc3-7633-4ffd-82da-d34000dfc0d6"
    character_ref_preprocessor_id: 397
    character_ref_strength: "Mid"
    contrast: 3.5
  llm_config:
    type: prompt
    provider_config:
      provider: openai
      model: gpt-5.4-mini
  speech_config:
    type: edge-tts
  transcription_config:
    model: base
    type: local
services:
  captions_config:
    font_path: default_font.ttf
  video_config:
    call_to_action_path: assets/call_to_action.png
    youtube_channel_url: https://www.youtube.com/channel/UCIXTGJvqvxWoWWstA66a2JQ
bots:
  image_story_bot:
    allowed_user_ids: [627370641]
    low_quality: false
  two_part_history_bot:
    allowed_user_ids: [627370641]
    low_quality: false
