main:
  # seed: 48B4LJV2SI
  output_path: output/
  history_config:
    source: config
    history:
      content: 'É exatamente isso, essa história maluca ocorreu ontem. Ela foi tomar banho, ligou o chuveirinho
          da privada e deixou o registro aberto. Em uma situação normal ele não vazaria mesmo aberto, MAS a
          torneira se soltou e começou a derramar MUITA água. Mesmo assim a gente não ouviu, acabamos dormindo.
          Até que, por eu ter um sono extremamente leve, senti a água se movendo perto da cama. Eu me levantei
          ASSUSTADO, achando que era um pesadelo kkkkk.


          Acabou que eu vi a água chegando quase na canela! Eu desci rapidamente pra desligar os eletrônicos,
          minha esposa acordou e começou a ficar NERVOSA. Eu peguei um rodo e comecei a jogar água pro ÚNICO
          ralo desse AP feito por IA (AP todo sem nexo). Ela começou a passar MAL por causa do susto e também
          por receio de ter queimado meu Steam Deck + TV recém-comprada.


          No final, eu consegui secar o AP depois de 2 horas passando o rodo e voltamos a dormir. Hoje, dia
          24 de dezembro, vi que nada queimou e, de quebra, a casa ficou limpinha. É GAIN ou LOSS?'
      description: Uma história de um banho descuidado que quase virou um desastre em casa.
      file_name: minha_esposa_alagou_o_apartamento
      reddit_community: r/RelatosDoReddit
      reddit_community_url_photo: https://styles.redditmedia.com/t5_72ljkj/styles/communityIcon_nhey0a1kj0jc1.png
      reddit_post_author: Funny-Ad-9414
      title: Minha esposa alagou o apartamento
  video_config:
    low_quality: true
    youtube_channel_id: UCTGjE7hWuBRNqU-OnVSzq3Q
    watermark_path: assets/watermark.png
    cover_duration: 5
    end_silece_seconds: 3
    padding: 50
    width: 1080
    height: 1920
  cover_config:
    title_font_size: 110
