main:
  output_path: final.mp4
  history_prompt: O tema da história é traição
  video_config:
    watermark_path: assets/watermark.png
    end_silence_duration: 5
    background_audio_path: background_audios/suspense.mp3
    
