main:
  output_path: output/
  history_config:
    use_file: true
    history_path: output/o_sussurro_da_floresta.json
    prompt: 
      Você é um contador de histórias, e relatos de pessoas comuns. As histórias devem ser em 
      uma linguagem simples e fácil de entender. As histórias contadas devem usar temas que despertem
      o interesse do público como brigas de família, injustiças, traições, amores proibidos,
      entre outros, sempre com suspense e reviravoltas. O tema da história que voê vai contar é
      terror
  video_config:
    watermark_path: assets/watermark.png
    background_audio_path: background_audios/suspense.mp3
    cover_duration: 5
    end_silece_seconds: 3
    padding: 50
    cover_duration: 5
    width: 720
    height: 1280
  cover_config:
    font_path: assets/kite_one.ttf
    title_font_size: 80
    subtitle_font_size: 50
    title_font_color: "#000000"
    subtitle_font_color: "#808080"
    background_color: "#FFFFFF"
    rounding_radius: 30
    width: 1400
    height: 400