main:
  # seed: KTEX8MJIOH
  output_path: output/
  history_config:
    source: config
    histories:
    -   content: 'Há muitos anos, após o nascimento do meu filho mais velho, eu precisava desesperadamente
            de um emprego. Eu estava vasculhando a seção de empregos de tantos jornais quanto podia encontrar.
            As opções eram escassas, pois a minha maior qualificação era ter terminado o Ensino Médio. Eu
            tive que ignorar os empregos de salário mínimo, pois custaria mais do que o salário que recebia.

            Curta e me siga para parte 2'
        description: ''
        file_name: a_razao_pela_qual_meu_ex_e_meu_ex_1
        reddit_community: r/pettyrevenge
        reddit_community_url_photo: https://styles.redditmedia.com/t5_2vg7t/styles/communityIcon_6ofkqruptzc71.png
        reddit_post_author: TwirlyShirley8
        title: A razão pela qual meu ex é meu ex - Parte 1
    -   content: Foi então que recebi uma ligação que mudaria tudo. Uma empresa estava procurando por alguém
            para uma posição que parecia ideal, embora eu não tivesse certeza se era qualificado. Decidi me
            inscrever e, mesmo sem grandes esperanças, fui chamado para uma entrevista. Minha mente estava
            a mil, e eu me perguntava se essa poderia ser a oportunidade que eu tanto precisava. O que eu
            não sabia era que essa decisão me levaria a um caminho inesperado e cheio de reviravoltas.
        description: ''
        file_name: a_razao_pela_qual_meu_ex_e_meu_ex_2
        reddit_community: r/pettyrevenge
        reddit_community_url_photo: https://styles.redditmedia.com/t5_2vg7t/styles/communityIcon_6ofkqruptzc71.png
        reddit_post_author: TwirlyShirley8
        title: A razão pela qual meu ex é meu ex - Parte 2
  video_config:
    low_quality: false
    youtube_channel_id: UCTGjE7hWuBRNqU-OnVSzq3Q
    watermark_path: assets/watermark.png
    cover_duration: 5
    end_silece_seconds: 3
    padding: 50
    width: 1080
    height: 1920
  cover_config:
    title_font_size: 110
