main:
  captions_config:
    enabled: true
    auto_generate: false
    upper: true
  output_path: output/
  video_config:
    low_quality: false
  history_config:
    histories:
    -   content: "Nunca imaginei que me encontraria em uma situação assim. Eu sou um homem de 24 anos, e Lisa\
            \ e eu estávamos juntos há um ano. Tudo entre nós parecia ótimo: comunicação sólida, encontros\
            \ emocionantes e uma conexão íntima que fluía naturalmente. Mas uma noite, ela trouxe à tona algo\
            \ que destruiu completamente minha percepção sobre nosso relacionamento.  \nEla queria ter uma\
            \ relação a três. A princípio, a ideia não me pareceu chocante. Afinal, as pessoas costumam experimentar,\
            \ e fantasias são normais. Mas então ela revelou a parte que fez meu estômago revirar. A terceira\
            \ pessoa que ela tinha em mente não era um estranho, não era um amigo—era meu irmão.  \nOuvir\
            \ essa sugestão me deixou paralisado. Ela falava sobre isso de forma tão casual, como se fosse\
            \ apenas uma ideia aventureira, algo emocionante, ao invés de profundamente perturbador. Para\
            \ ela, era uma oportunidade de vivenciar algo único—dois homens que se pareciam, duas versões\
            \ de mim ao mesmo tempo. Mas para mim, isso era impensável.  \nQuanto mais ela explicava, pior\
            \ ficava. Ela não via problema algum, não entendia por que eu deveria me sentir desconfortável.\
            \ Para ela, era apenas uma fantasia, algo que ao menos poderíamos discutir. Mas eu não conseguia\
            \ nem processar a ideia. Envolver a família em algo tão íntimo ultrapassava uma linha que eu nem\
            \ sabia que precisava ser desenhada.  \nA conversa rapidamente se transformou em frustração. Ela\
            \ desconsiderou meu repúdio como uma reação exagerada, me rotulando como cabeça- dura por não\
            \ cogitar a ideia. Mas não havia debate a ser feito. Algumas coisas simplesmente não estão abertas\
            \ à discussão, e essa era uma delas.  \nSaí daquela noite, precisando de ar, precisando de distância.\
            \ Um ano de amor e confiança se desfez em um único momento. Algumas linhas, uma vez cruzadas,\
            \ nunca podem ser redesenhadas.
            \ E você, qual sua opinião sobre isso? Curta, me siga e deixe nos comentários."
        description: A história de um jovem que enfrenta um pedido inusitado de sua namorada, desafiando os
            limites do que ele considera aceitável.
        file_name: minha_namorada_queria_ter_relacoes
        gender: male
        reddit_community: r/stories
        reddit_community_url_photo: https://styles.redditmedia.com/t5_2qi02/styles/communityIcon_05zxv6e6eq6b1.png
        reddit_post_author: NoFortune1676
        title: Minha Namorada Queria Ter Relações Comigo e Com Meu Irmão
    -   content: 'Sim, eu sou mulher. Sim, meu marido tem amigas. Ele não é gay e não está envolvido com ninguém
            fora do nosso relacionamento. Todo mundo fala sobre machismo, que os homens tratam as mulheres
            mal, o que realmente é verdade. Mas quando eles tentam ser diferentes... aí o sujeito encontra
            uma namorada ou esposa e agora precisa assinar um contrato de exclusividade feminina. É como se
            ele não pudesse nem tratar bem outra mulher. Amizade? Nem pensar. Não pode olhar para ninguém
            na rua. Tem que deixar de seguir todas as mulheres e se restringir a conversar, no máximo, com
            a mãe e a irmã.


            De onde as mulheres tiraram isso, sério? Elas agem como se fosse um preventivo para traição, mas
            isso simplesmente não existe! E digo mais: um homem sem amizade com mulheres é um sinal vermelho,
            afinal, um homem decente precisa saber se socializar com mulheres que não estão interessadas romanticamente
            nele.


            Meu marido tem amigas no trabalho também, e de vez em quando ele leva um salgado ou doce para
            elas, porque elas também são gentis. Elas trazem lembrancinhas quando viajam, dividem o lanche,
            livram ele de situações complicadas quando a chefe está de mau humor, etc. Eu sou super feliz
            e descontraída porque eu escolhi uma pessoa de caráter e muito agradável. Então, é óbvio que outras
            pessoas vão gostar da companhia dele e, para mim, isso é motivo de orgulho. E para você? Qual sua opinião 
            sobre isso? Curta, me siga e deixe nos comentários.'
        description: Uma mulher compartilha sua visão sobre a importância da amizade entre homens e mulheres
            em relacionamentos.
        file_name: homem-casado-tem-que-ter-amiga-mulher
        gender: female
        reddit_community: r/opiniaoimpopular
        reddit_community_url_photo: https://styles.redditmedia.com/t5_50qq3m/styles/communityIcon_hvv1x9e0jbi91.png
        reddit_post_author: ImKirell
        title: Homem casado tem que ter amiga mulher
    -   content: 'Em janeiro de 2024, eu, um homem de 17 anos, acordei decidido a andar de bicicleta. No entanto,
            ao me lembrar que minha bicicleta estava um pouco desalinhada, decidi levá-la para consertar em
            uma oficina perto da minha casa. A oficina ficava a cerca de 10 minutos a pé, e como o calor estava
            insuportável, fui sem camisa. Ao chegar, percebi que a oficina estava fechada, provavelmente estavam
            de recesso. Então, subi na bicicleta e fui esperar o sinal abrir para atravessar uma avenida e
            voltar para casa. Estava próximo a um ponto de ônibus, próximo a uma faixa de pedestres, quando,
            do nada, ouvi um assobio. Quando olhei para trás, vi um homem de uns 50 ou 60 anos a poucos passos
            de distância de mim. Só havia aquele homem e uma senhora ao nosso redor. Assim que o encarei,
            ele lambeu os lábios e me avaliou de cima a baixo. Tive certeza absoluta de que ele estava tentando
            me assediar. Naquele momento, o sangue ferveu dentro de mim, afinal, eu era menor de idade. Menor
            ou não, ninguém merece que um velho se comporte daquela forma, olhando para o seu corpo e lambendo
            os lábios. Eu fiquei paralisado, sem saber o que fazer. Como estávamos perto de uma favela, me
            preocupei que discutir com ele pudesse trazer problemas para mim. No entanto, eu nunca o havia
            visto antes, então resolvi confrontá-lo. Peguei a bicicleta com a mão e fui atrás dele. Começou
            uma conversa tensa, e eu gritei: ''E aí, parceiro? Você quer arrumar para a cabeça?''. O cara
            ficou paralisado, sem acreditar que eu estava seguindo-o.

            Curta e me siga para parte 2'
        file_name: sou_babaca_por_bater_em_um_tarado_1
        gender: male
        reddit_community: r/EuSouOBabaca
        reddit_community_url_photo: https://styles.redditmedia.com/t5_2h1drm/styles/communityIcon_rl5tuzyrh8nb1.png
        reddit_post_author: Many-Sign3681
        title: Sou babaca por bater em um tarado? - Parte 1
    -   content: 'Ele começou a alegar que era casado e que eu estava vendo maldade onde não havia. Mas, do
            nada, ele entrou em uma loja de LED e começou a gritar: ''Esse menino me roubou!!'', me acusando
            de roubo. Eu estava com uma aparência um pouco suspeita, então isso complicou minha situação.
            Tentei gritar que ''Esse velho é um pedófilo'', mas os atendentes da loja não entenderam nada.
            Quando o homem percebeu que ninguém acreditou nele, saiu correndo para outra loja, desesperado
            para fugir de mim. E eu estava prestes a rebocar a cara dele. Estávamos na Avenida Anchieta em São Paulo,
            onde há várias lojas. Deixei minha bicicleta no chão, ele entrou em um mecânico para se esconder,
            e eu o segui. Cada um gritava o que pensava, e quando ele me lançou uma pedra, o caos aumentou.
            Um grupo de motoboys se juntou ao redor, enquanto eu tentava explicar a situação para eles, mas
            o velho continuava gritando que eu tinha roubado ele. Ele jogou duas pedras, mas não me atingiu.
            Os mecânicos, percebendo a situação, meio que expulsaram o velho de lá para evitar problemas.
            De repente, ele saiu do mecânico com um cano de ferro e veio em minha direção. Eu sai correndo
            junto com os motoboys, e durante o tumulto, o velho se aproximou da minha bicicleta e começou
            a bater com o cano nela. Ouvia os espectadores dizendo: ''Irmão, vai pra casa, esse tiozinho tá
            maluco''. Quando ele parou de agredir a bicicleta e lançou o cano na minha direção, soube que
            precisava agir. O cano caiu no chão, entre nós dois, e quando ele se abaixou para pegá-lo, eu
            corri em sua direção, e dei uma joelhada na cara dele. O velho caiu no chão, e por
            um momento, eu fiquei apenas observando. Mas logo os motoboys nos separaram, e eu subi na minha
            bicicleta e fui embora.
            
            Na sua opinião, eu fui babaca por fazer isso tudo por um assobio? Curta, me siga e deixe nos 
            comentários.
            '
        file_name: sou_babaca_por_bater_em_um_tarado_2
        gender: male
        reddit_community: r/EuSouOBabaca
        reddit_community_url_photo: https://styles.redditmedia.com/t5_2h1drm/styles/communityIcon_rl5tuzyrh8nb1.png
        reddit_post_author: Many-Sign3681
        title: Sou babaca por bater em um tarado? - Parte 2