language: pt-br
proxies:
  cover_config:
    title_font_size: 150
  image_generation_config:
    type: mock
  llm_config:
    type: mock
  history_adaptation_llm_config:
    type: mock
  reddit_config:
    type: json
  speech_config:
    type: edge-tts
    default_rate: 1.2
  transcription_config:
    model: base
    type: local
services:
  captions_config:
    font_path: default_font.ttf
  video_config:
    call_to_action_path: assets/call_to_action.png
    youtube_channel_url: https://www.youtube.com/channel/UCIXTGJvqvxWoWWstA66a2JQ
    ffmpeg_params: ["-crf", "28", "-preset", "fast"]
bots:
  image_story_bot:
    allowed_user_ids: [627370641]
    low_quality: false
  satisfying_bot:
    allowed_user_ids: [627370641]
    low_quality: false
evaluation:
  subreddits:
    - pettyrevenge
    - AmItheAsshole
    - RelationshipAdvice
    - TrueOffMyChest
    - AskReddit
    - ExplainLikeImFive
    - MaliciousCompliance
    - Antiwork
    - EuSouOBabaca
    - RelatosDoReddit
    - relacionamentos
  min_chars: 500
  max_chars: 15000
