main:
  seed: 48B4LJV2SI
  output_path: output/
  history_config:
    source: config
    history:
      content: 'Há alguns anos, descobri que meu (agora ex) marido estava tendo múltiplos casos extraconjugais.
          Entrei em contato com as mulheres na tentativa de descobrir o que estava acontecendo, cronogramas,
          etc. A maioria das mulheres era adorável e eu não sentia desprezo ou raiva por elas; eram vítimas
          de mentiras e enganos também. MAS, uma mulher adotou uma abordagem diferente: ela foi rude e abusiva,
          me acusando de ser controladora, fria, gorda (sou apenas uma dessas coisas e não sou fria), etc. Infelizmente,
          ela estava na Irlanda e nós estávamos na Austrália, então não havia chance de confrontá-la. Tentei
          apenas seguir em frente e lidar com meus problemas reais. MAS, não consegui me livrar da audácia.
          Então eu procurei as redes sociais dela. Ela era OBSECADA por "Australian MasterChef". Obcecada! Sendo
          fã eu mesma, sabia que o show era exibido e concluído na Austrália antes de ser transmitido na Irlanda.
          Então eu fiz uma captura de tela do prato vencedor e mencionei ela em um tweet contendo os detalhes
          do vencedor, do segundo colocado e a foto do prato vencedor. Depois, coloquei um alarme no meu celular
          e fiz exatamente a mesma coisa um ano depois. Após o segundo spoiler, ela colocou a conta do Twitter
          dela em privado.'
      description: Uma mulher decide se vingar da amante do ex-marido após ser insultada.
      file_name: a_amante_do_meu_marido
      reddit_community: r/pettyrevenge
      reddit_community_url_photo: https://styles.redditmedia.com/t5_2vg7t/styles/communityIcon_6ofkqruptzc71.png
      reddit_post_author: nelinthemirror
      title: A amante do meu marido foi rude comigo, então eu arruinei sua coisa favorita, duas vezes
  video_config:
    low_quality: false
    youtube_channel_id: UCTGjE7hWuBRNqU-OnVSzq3Q
    watermark_path: assets/watermark.png
    cover_duration: 5
    end_silece_seconds: 3
    padding: 50
    width: 1080
    height: 1920
  cover_config:
    title_font_size: 110
