captions_config:
    color: '#FFFFFF'
    fade_duration: 0
    font_path: assets/bangers.ttf
    font_size: 110
    stroke_color: '#000000'
    stroke_width: 8
    upper: true
cover_config:
    title_font_size: 110
histories_path: flask_server/static/histories/
seed: BBBHI91R19
video_config:
    audio_speed_rate: 1.0
    cover_duration: 5
    end_silece_seconds: 3
    height: 1920
    low_quality: false
    low_resolution: false
    padding: 60
    watermark_path: null
    width: 1080
    youtube_channel_id: UCIXTGJvqvxWoWWstA66a2JQ
