captions_config:
    color: '#FFFFFF'
    fade_duration: 0
    font_path: assets/bangers.ttf
    font_size: 90
    stroke_color: '#000000'
    stroke_width: 8
    upper: true
cover_config:
    title_font_size: 110
histories_path: web/static/histories/
seed: BBBHI91R19
video_config:
    cover_duration: 4
    end_silece_seconds: 1
    height: 1920
    padding: 60
    watermark_path: null
    width: 1080
    youtube_channel_id: UCIXTGJvqvxWoWWstA66a2JQ